version: '3.8'

services:
  namesrv:
    image: apache/rocketmq:5.3.1
    container_name: rocketmq-namesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    environment:
      - JAVA_OPT_EXT=-Xms256m -Xmx256m

  broker:
    image: apache/rocketmq:5.3.1
    container_name: rocketmq-broker
    ports:
      - "10911:10911"
      - "10909:10909"
    depends_on:
      - namesrv
    command: sh mqbroker -n namesrv:9876 --enable-proxy -c /home/rocketmq/rocketmq-5.3.1/conf/broker.conf
    environment:
      - JAVA_OPT_EXT=-Xms256m -Xmx256m
    volumes:
      - ./broker.conf:/home/rocketmq/rocketmq-5.3.1/conf/broker.conf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    ports:
      - "9201:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
